[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "script"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "chainlink/=lib/chainlink/",
    "solmate/=lib/solmate/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
