[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "chainlink/=lib/chainlink/",
    "solmate/=lib/solmate/",
]
[dependencies]
smartcontractkit/chainlink = { git = "https://github.com/smartcontractkit/chainlink", tag = "v1.2.0" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
